language: node_js
node_js:
  - 6

addons:
  sauce_connect: true

before_script:
  - npm run serve &
  - sleep 5
  - curl --retry 10 --retry-delay 2 -v http://localhost:8080

script:
  - npm run test-ci



