language: node_js

dist: trusty

addons:
  firefox: 'latest'

node_js:
  - 6

before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

cache:
  directories:
  - node_modules

before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

before_script:
 - npm start &
 - sleep 20

script: npm run test:ci
