language: node_js
node_js:
- 6
before_script: patch -p0 < .config/awesome-typescript-loader.patch
before_deploy: npm run build:prod
deploy:
  provider: s3
  bucket: access.sparks.network
  region: "us-west-2"
  skip_cleanup: true
  local_dir: dist
  on:
    all_branches: true
  secret_access_key:
    secure: S9DOfgarpQka44xv1wZ84gL14HMtCKlHcQ/FFgTpwinTBaz6faJhAzubt92GV+1DMizM8C90lkMf6x8kmWuZpdoySyFtBHdRZnBAk6oMs+5ji3uSi0n56UDDpbdP8l6LHf2YoIKPS6Ve4Cv7/9N60XmQDnvq3DPe7g+gQoiM2jsb1obAjb6c2W9RxlG1iUj3ACByhNZaLAyf10c5q5TX1faK7kFyp1Jdvfc95qw3O+xkkXGnKmJNm6cvLsMtMU8jtYeBBuFJq8RXNqVJtTPQ3gOqioCUfEj/GTt1eNnc8zq6gFCj4K73pzzdsWcoHk2KMGwKC6FI7aam0vxHgbGTi9n9z/p6jwg1FRwugETUvY42KElWucEl9hhFUIijZuiWnShRcx+zKaNcsmPIC00wQjFQ777cf3TdYbazEIp9RGTia+PMqSa5L0ustmempOSWN3c5ateO9AnabSKkoenN4+sjS7s5O+6rr1+jWKZQjPslcrVRinmEnKcQWYpBSypxKViaX/bMaZAxx2HgahR/5EZjbag7q1kxGkr5xQYaDp3QjMUI7NL79sG/cgRphi/qSVcInj09iC4hcr45HcWNr3CZa5qbAZq8af2FwnUYUHpuuIFNJ7TB2omPDMCIcxcVKUPOTxdVUCD59v4e/h0VbBtJOjtTdEcbKnWNOZTGl7w=
  access_key_id:
    secure: lSzIhCHs2gRIFdWQxiG7yl6keMV97vS4mMX58QGKBsLcNxwAEuV2193uDaKdqx8gLpoS6GYgv45sNZs+LJ9wnxJmyTwEyeAACD4oJkLv+FXgBTvvRIcIHPbFbU9D7CDLHp41Hs34mHQIVD+K8epJsg+B//lSFfIHn91EORjYhd/B0WLJRwZxvwGZh/wb+1QA6ga7cd2+ZOJRE0MKSAbSoBy82qe0elSKHgLfu6eO6MryfcLtXLIK2pU0+daX9HGcJgqQOzgmN2/iHuARfqYmAdAI3Pm5+lavUZtcVa4aodxJwObd8+Vh0AQyXphpN9ZRESaluUITTNrVCsBVD9BXZrNG9AUMVN4lbvWspuW/Ko5fxje+y4toefp+cPDbNOtp/l/W+SEtlB65rmULRI3meatY7FaHTkd32ZOHQTyV+KNQwqVCERMMnVb8Buhe4mywH3y2P3rq+RcrqGrU9PbZKRMutKz2BJjGswe8LI52HcwEaVSKBu3dclohi9pn4y+NpDUYjV7a1LgHMDuRAxHca6zDjFh6A3uvjpizii+gNjRSH0GsHmFyKExJlLUokS/jDMCnSjUejIEJg9Kx9Nz7LlpiAoJhqM42MzzmUQFznKfYeslhw9aVmWHSFYJbxXv9Jua0Jc4q+kAHpRC2CWY5Xae+VP1nwy7WPeDZgGyTxT8=
